apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    app: console
spec:
  selector:
    app: console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP # Change to NodePort if LoadBalancer is not supported
