name: Deploy Combined Manifest to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Combine All Manifests Dynamically
      run: |
        mkdir -p combined
        cat manifests/*.yaml > combined/all.yaml

    - name: Deploy to gh-pages
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions@users.noreply.github.com"
        git fetch origin gh-pages || echo "No gh-pages branch exists yet"
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        mv combined/all.yaml .
        rm -rf combined
        git add .
        git commit -m "Deploy combined manifest to gh-pages" || echo "Nothing to commit"
        git push origin gh-pages --force
